In [1]:
print("Hello World !")

Hello World !


In [2]:
Nom = input("Entrez votre NOM : ")

Entrez votre NOM : salim


In [3]:
age = int(input("Entrez votre âge : "))
poids = float(input("Entrez votre poids : "))

Entrez votre âge : 12
Entrez votre poids : 77.5


In [4]:
nom = "azghay"
age = 21
poids = 75.5
valider = True

In [5]:
age = 25   # mise à jour de la valeur de la variable "âge"

In [3]:
nom_liste = [1, 2, 3, 4] # liste initialiser
nom_liste2 = [] # liste vide

In [7]:
nom_liste = []

In [8]:
nom_liste = [1, 2, 3, 4]
print(nom_liste)# afficher tous les éléments de la liste

[1, 2, 3, 4]


In [9]:
print(nom_liste[0]) # afficher 1
print(nom_liste[2]) # afficher 3

1
3


In [10]:
print(nom_liste[-1]) # afficher 4
print(nom_liste[-3]) # afficher 2

4
2


In [11]:
nom_liste[0] = 5 # modifies l’élément de l’index 0
print(nom_liste) # afficher [5,2,3,4]

[5, 2, 3, 4]


In [12]:
nom_liste = [1, 2, 3, 4]
nom_liste.append(11)
print(nom_liste) # afficher [1,2,3,4,11]

[1, 2, 3, 4, 11]


In [13]:
nom_liste = [1, 2, 3, 4]
nom_liste.inssert(2,11)  # ajouter au millier de la liste
print(nom_liste) # afficher [1,2,11,3,4]
nom_liste.inssert(0,0)  # ajouter au début de la liste
print(nom_liste) # afficher [0,1,2,11,3,4]

AttributeError: 'list' object has no attribute 'inssert'

In [14]:
nom_liste = [1, 2, 3, 4]
nom_liste.insert(2,11)  # ajouter au millier de la liste
print(nom_liste) # afficher [1,2,11,3,4]
nom_liste.insert(0,0)  # ajouter au début de la liste
print(nom_liste) # afficher [0,1,2,11,3,4]

[1, 2, 11, 3, 4]
[0, 1, 2, 11, 3, 4]


In [15]:
nom_liste = [1,2,3,4,2]
nom_liste.remove(2) # supprime la première élément égale 2
print(nom_liste) # affiche [1,3,4,2]

ele = nom_liste.pop() # supprime et retourne le dernier élément
print(ele) # affiche 2
print(nom_liste) # affiche [1,3,4]

[1, 3, 4, 2]
2
[1, 3, 4]


In [16]:
liste = [1, 2, 3, 4, 5]

In [17]:
if 4 > 5:
    print("True")
else:
    print("False")

False


In [18]:
if 4 > 5:
    print("PHP")
elif 4 > 3:
    print("CSS")
else:
    print("JAVA")

CSS


In [19]:
j = 0
while j < 5:

SyntaxError: incomplete input (3900355771.py, line 2)

In [20]:
j = 0
while j < 5:
    print(j,end=' ')
    j += 1

0 1 2 3 4 

In [21]:
fruits = ["ananas", "banane", "avocat", "cerise"]
for fruit in fruits:
    print(fruit , end=' ')

ananas banane avocat cerise 

In [22]:
for i in range(5):
    print(i, end=' ')

0 1 2 3 4 

In [1]:
a = 2
b = 3
if a > b:
    print("le max est : ",a)
else:
    print("le max est : ",b)

le max est :  3


In [2]:
a = 9
if a < 0:
    
    print("a est negative ")
elif a == 0:
    print("a est null ")
else:
    print("a est positive ")

a est positive 


In [4]:
nom_liste = [1, 2, 3, 4] # liste initialiser
nom_liste2 = [] # liste vide

In [5]:
## le mode lecture 

In [6]:
ele = open("fichier.txt","r+")
ele.write("banan")
ele.write("ananas")

FileNotFoundError: [Errno 2] No such file or directory: 'fichier.txt'

In [7]:
ele = open("fichier.txt","w+")
ele.write("banan")
ele.write("ananas")

6

In [8]:
ele = open("fichier.txt","w")
ele.write("banan")
ele.write("ananas")

6

In [9]:
ele = open("fichier.txt","a+")
ele.write("pomme")

5

In [10]:
with open("fichier.txt","r+") as f:
    print(f.read())

bananananas


In [11]:
ele = open("fichier.txt","w")
ele.write("banan \n")
ele.write("ananas \n")
ele.close()

In [12]:
ele1 = open("fichier.txt","a+")
ele1.write("pomme")
ele1.close()

In [13]:
with open("fichier.txt","r+") as f:
    print(f.read())

banan 
ananas 
pomme


In [14]:
import numpy as np

# Création d'un tableau à partir d'une liste
list = [1, 2, 3, 4, 5]
array = np.array(list)

print(array) # afficher [1 2 3 4 5]


[1 2 3 4 5]


In [15]:
# Création d'un tableau de zéros :

In [16]:
import numpy as np

# Création d'un tableau de zéros
zeros_array = np.zeros((2, 3))

print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Création d'un tableau de uns

In [18]:
import numpy as np

# Création d'un tableau de 1
ones_array = np.ones((3, 4))

print(ones_array)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [19]:
# Création d'un tableau vide

In [20]:
import numpy as np

# Création d'un tableau vide
my_array = np.empty((2, 3))

print(my_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# Création d'un tableau d'une séquence de nombres

In [22]:
import numpy as np

# Création d'un tableau d'une séquence de nombres
range_array = np.arange(0, 10, 3)

print(range_array) # afficher [0 3 6 9]

[0 3 6 9]


In [23]:
$ Addition :

SyntaxError: invalid syntax (1625354571.py, line 1)

In [24]:
#@ Addition

In [25]:
@#Addition

SyntaxError: invalid syntax (478412749.py, line 1)

In [26]:
# Addition

In [27]:
import numpy as np

x = np.array([1, 1, 5])
y = np.array([7, 5, 6])
addition = a + b
print(addition) # [6 4 1]


12


In [28]:
import numpy as np

x = np.array([1, 1, 5])
y = np.array([7, 5, 6])
addition = x + y
print(addition) # [8 6 11]

[ 8  6 11]


In [29]:
# Soustraction 

In [30]:
import numpy as np

x = np.array([1, 1, 5])
y = np.array([7, 5, 6])
soustraction = x - y
print(soustraction) # [6 4 1]

[-6 -4 -1]


In [31]:
import numpy as np

x = np.array([1, 1, 5])
y = np.array([7, 5, 6])
soustraction = y - x
print(soustraction) # [6 4 1]

[6 4 1]


In [32]:
# Multiplication

In [33]:
import numpy as np

x = np.array([1, 3, 3])
y = np.array([5, 5, 4])
z = x * y
print(c) # afficher [5 15 12]


NameError: name 'c' is not defined

In [34]:
import numpy as np

x = np.array([1, 3, 3])
y = np.array([5, 5, 4])
z = x * y
print(z) # afficher [5 15 12]

[ 5 15 12]


In [35]:
# Division 

In [36]:
import numpy as np

x = np.array([6, 3, 12])
y = np.array([2, 2, 3])
z = x / y
print(z) # afficher [3 1,5 4]

[3.  1.5 4. ]


In [37]:
import numpy as np

x = np.array([6, 3, 12])
y = np.array([2, 2, 3])
z = x / y
print(z) # afficher [3. 1.5 4.]

[3.  1.5 4. ]


In [38]:
# Puissance

In [39]:
import numpy as np

x = np.array([6, 3, 7])
y = np.power(x, 2)
print(z) # afficher [36 9 49]

[3.  1.5 4. ]


In [40]:
import numpy as np

x = np.array([6, 3, 7])
y = np.power(x, 2)
print(y) # afficher [36 9 49]

[36  9 49]


In [41]:
# tan()

In [42]:
# sqrt()

In [43]:
import numpy as np

a = np.array([64, 49, 16])
b = np.sqrt(a)
print(b) # [8. 7. 4.]


[8. 7. 4.]


In [44]:
# exp()

In [45]:
import numpy as np

x = np.array([1, 2, 3])
y = np.exp(x)
print(y) # afficher [ 2.71828183  7.3890561  20.08553692]


[ 2.71828183  7.3890561  20.08553692]


In [46]:
# log()

In [47]:
import numpy as np

x = np.array([1, 10, 100])
y = np.log(a)
print(y) # afficher [0.         2.30258509 4.60517019]


[4.15888308 3.8918203  2.77258872]


In [48]:
# Création d'un tableau numpy à partir d'une liste de listes

In [49]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]])
print(x)


[[1 2 3]
 [4 5 6]]


In [50]:
# Accès aux éléments d'un tableau numpy

In [51]:
import numpy as np

x = np.array([1, 2, 3, 4, 5])
print(x[0]) # accès au premier élément
print(x[-1]) # accès au dernier élément
print(x[1:5]) # accès aux éléments de l'indice 1 à l'indice 4 (non inclus)


1
5
[2 3 4 5]


In [52]:
# Fonctions mathématiques sur les tableaux numpy 

In [53]:
import numpy as np

x = np.array([1, 6, 3])
print(np.mean(x)) # calcul de la moyenne
print(np.std(x)) # calcul de l'écart-type


3.3333333333333335
2.0548046676563256


In [54]:
# Moyenne 

In [55]:
# Médiane

In [56]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
median = np.median(array)

print("Médiane:Me = ", median)


Médiane:Me =  3.0


In [57]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
median = np.median(array)

print("Médiane est : Me = ", median)

Médiane est : Me =  3.0


In [58]:
# Écart-type

In [59]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
ecart_type = np.std(array)

print("Écart-type est : ", ecart_type)


Écart-type est :  1.4142135623730951


In [60]:
# Variance 

In [61]:
import numpy as np

array = np.array([1, 2, 3, 4, 5])
variance = np.var(array)

print("Variance est : ", variance)


Variance est :  2.0


In [63]:
# Addition de deux matrices

In [64]:
import numpy as np

# deux matrices aléatoires
x = np.random.rand(3, 3)
y = np.random.rand(3, 3)

# addition de deux matrices
z = x + y

print(z)


[[0.6247477  0.8295561  1.27115816]
 [0.15336939 0.29738603 0.8123383 ]
 [1.2456384  1.70230205 1.48953837]]


In [65]:
# Multiplication de deux matrices 

In [66]:
import numpy as np

# deux matrices aléatoires
x = np.random.rand(3, 3)
y = np.random.rand(3, 3)


# multiplication de deux matrices
z = np.dot(x, y)

print(z)


[[1.19747204 0.47175178 0.47840228]
 [0.73878886 0.24374819 0.30743349]
 [1.15037036 0.76279653 0.34356674]]


In [67]:
# Calcul de l'inverse d'une matrice 

In [68]:
import numpy as np

# une matrice aléatoire
x = np.random.rand(2, 2)

# calcul de l'inverse d'une matrice
y = np.linalg.inv(x)

print(b)


[8. 7. 4.]


In [69]:
# Filtrage basique avec numpy.where() :


In [70]:
import numpy as np

# Créer un tableau NumPy aléatoire
array = np.random.rand(5, 5)

# Filtrer les éléments supérieurs à 0.5
filtred_array = np.where(array > 0.5, arr, 0)

print(filtred_array)


NameError: name 'arr' is not defined

In [71]:
import numpy as np

# Créer un tableau NumPy aléatoire
arr = np.random.rand(5, 5)

# Filtrer les éléments supérieurs à 0.5
filtred_arr = np.where(arr > 0.5, arr, 0)

print(filtred_arr)


[[0.77955337 0.         0.94656439 0.         0.        ]
 [0.84314248 0.         0.         0.57125914 0.        ]
 [0.58759183 0.         0.58921935 0.         0.        ]
 [0.         0.84720949 0.         0.534628   0.        ]
 [0.7623776  0.         0.85819061 0.77561547 0.76357509]]


In [72]:
# Filtrage avec numpy.logical_and() et numpy.logical_or()

In [73]:
import numpy as np

# Créer un tableau NumPy aléatoire
array = np.random.rand(5, 5)

# Filtrer les éléments entre 0.2 et 0.8
filtred_array = np.where(np.logical_and(array > 0.2, array < 0.8), array, 0)

print(filtred_array)


[[0.73590043 0.         0.53249924 0.         0.        ]
 [0.21087625 0.         0.37932256 0.3976383  0.55375648]
 [0.5499532  0.         0.         0.         0.        ]
 [0.         0.51066709 0.27258579 0.28039089 0.        ]
 [0.         0.         0.         0.37698923 0.        ]]


In [74]:
# Filtrage avec numpy.ma.masked_where() 

In [75]:
import numpy as np

# Créer un tableau NumPy aléatoire
array = np.random.rand(5, 5)

# Créer un masque pour filtrer les éléments inférieurs à 0.5
masked = np.ma.masked_where(array < 0.5, arr)

print(masked)


[[0.7795533680609955 -- 0.9465643910250024 -- 0.03448911294942025]
 [-- -- -- 0.5712591402262609 --]
 [-- 0.34867111909874937 0.5892193527458839 -- 0.1784374531048113]
 [0.2768372023573249 0.8472094875266185 0.11218615201208126
  0.5346280048292184 --]
 [0.7623776009764504 -- -- 0.7756154733016262 --]]


In [76]:
 # la racine carrée de x

In [77]:
import math as m
print(math.sqrt(49)) # afficher 7.0

NameError: name 'math' is not defined

In [78]:
import math as m
print(m.sqrt(49)) # afficher 7.0

7.0


In [79]:
import math as m
print(m.pow(3, 2)) # afficher 9.0

9.0


In [82]:
import math as m
print(m.floor(3.2)) # afficher 3.0

3


In [83]:
import math as m
print(m.ceil(3.2)) # afficher 4.0

4


In [85]:
import math as m
print(m.cos(m.pi)) # afficher -1.0


-1.0
